[package]
name = "hqs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
grim-rs = "0.1.3"
image = "0.25.9"

[patch.crates-io]
grim-rs = { git = "https://github.com/Jeremis70/grim-rs" }
